// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/test/entities"
)

// DoctorRepository is an autogenerated mock type for the DoctorRepository type
type DoctorRepository struct {
	mock.Mock
}

// ListDoctor provides a mock function with given fields:
func (_m *DoctorRepository) ListDoctor() ([]entities.Doctor, error) {
	ret := _m.Called()

	var r0 []entities.Doctor
	if rf, ok := ret.Get(0).(func() []entities.Doctor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Doctor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
